### ISSUE TITLE
Implement backOrFrontOf Format

### ISSUE THREAD

**Issue by carmo-evan** [carmo-evan/strtotime#14]
## Test Cases

Input: `November 15 2019 back of 7pm`.
Output: `1573845300` equivalent to `15/11/2019 19:15:00`.

Input: `November 15 2019 front of 7pm`.
Output: `1573843500` equivalent to `15/11/2019 18:45:00`.

**Comment by evalevanto** [comment]
Hey @carmo-evan i want to take this up. Can i submit a PR?

**Comment by carmo-evan** [comment]
Go for it! Thank you for the help!

**Comment by evalevanto** [comment]
#16 💯 :)

**Comment by carmo-evan** [comment]
@evalevanto merge to master. Thank you very much! Closing this issue.
